## detect_r_function_names() ----

test_that("detect_r_function_names() works - No functions", {
  with_local_project({
    initialize_project(quiet = TRUE)

    dir.create(build_abs_path("R"))

    asserts <- build_abs_path("R", "asserts.R")
    content <- c(
      "# There is no function here"
    )

    writeLines(content, asserts)

    expect_silent({
      x <- detect_r_function_names()
    })
    expect_true(inherits(x, "list"))
    expect_equal(length(x), 2L)
    expect_true("external" %in% names(x))
    expect_true("internal" %in% names(x))
    expect_null(x[[1]])
    expect_null(x[[2]])
  })
})

test_that("detect_r_function_names() works - No NAMESPACE", {
  with_local_project({
    initialize_project(quiet = TRUE)

    dir.create(build_abs_path("R"))

    asserts <- build_abs_path("R", "asserts.R")
    content <- c(
      "#' @noRd",
      "`%||%` <- function(x, y) {",
      "  if (is.null(x)) y else x",
      "}",
      "",
      "#' @noRd",
      "path_proj <- function() usethis::proj_get()",
      "",
      "#' @noRd",
      "try_read <- function(file) {",
      "  tryCatch(read_utf8(file), error = function(e) {",
      "    stop(e)",
      "  })",
      "}"
    )

    writeLines(content, asserts)

    expect_silent({
      x <- detect_r_function_names()
    })

    expect_true(inherits(x, "list"))
    expect_equal(length(x), 2L)
    expect_true("external" %in% names(x))
    expect_true("internal" %in% names(x))
    expect_null(x[[1]])
    expect_equal(length(x[[2]]), 3L)
    expect_true(x[[2]][1] == "`%||%`")
    expect_true(x[[2]][2] == "path_proj")
    expect_true(x[[2]][3] == "try_read")
  })
})

test_that("detect_r_function_names() works - R functions + Empty NAMESPACE", {
  with_local_project({
    initialize_project(quiet = TRUE)

    dir.create(build_abs_path("R"))

    asserts <- build_abs_path("R", "asserts.R")
    content <- c(
      "#' @noRd",
      "`%||%` <- function(x, y) {",
      "  if (is.null(x)) y else x",
      "}",
      "",
      "#' @noRd",
      "path_proj <- function() usethis::proj_get()",
      "",
      "#' @noRd",
      "try_read <- function(file) {",
      "  tryCatch(read_utf8(file), error = function(e) {",
      "    stop(e)",
      "  })",
      "}"
    )

    writeLines(content, asserts)

    file.create(build_abs_path("NAMESPACE"))

    expect_silent({
      x <- detect_r_function_names()
    })

    expect_true(inherits(x, "list"))
    expect_equal(length(x), 2L)
    expect_true("external" %in% names(x))
    expect_true("internal" %in% names(x))
    expect_null(x[[1]])
    expect_equal(length(x[[2]]), 3L)
    expect_true(x[[2]][1] == "`%||%`")
    expect_true(x[[2]][2] == "path_proj")
    expect_true(x[[2]][3] == "try_read")
  })
})

test_that("detect_r_function_names() works - R functions + NAMESPACE", {
  with_local_project({
    initialize_project(quiet = TRUE)

    dir.create(build_abs_path("R"))

    asserts <- build_abs_path("R", "asserts.R")
    content <- c(
      "#' @noRd",
      "`%||%` <- function(x, y) {",
      "  if (is.null(x)) y else x",
      "}",
      "",
      "#' @noRd",
      "path_proj <- function() usethis::proj_get()",
      "",
      "#' @noRd",
      "try_read <- function(file) {",
      "  tryCatch(read_utf8(file), error = function(e) {",
      "    stop(e)",
      "  })",
      "}"
    )

    writeLines(content, asserts)

    namespace <- build_abs_path("NAMESPACE")
    content <- c(
      "## Generated by roxygen2: do not edit by hand",
      "",
      "export(try_read)"
    )

    writeLines(content, namespace)

    expect_silent({
      x <- detect_r_function_names()
    })

    expect_true(inherits(x, "list"))
    expect_equal(length(x), 2L)
    expect_true("external" %in% names(x))
    expect_true("internal" %in% names(x))
    expect_equal(length(x[[1]]), 1L)
    expect_true(x[[1]][1] == "try_read")
    expect_equal(length(x[[2]]), 2L)
    expect_true(x[[2]][1] == "`%||%`")
    expect_true(x[[2]][2] == "path_proj")
  })
})
