## extract_exported_r_function_names() ----

test_that("extract_exported_r_function_names() works - No NAMESPACE", {
  with_local_project({
    initialize_project(quiet = TRUE)

    expect_null(extract_exported_r_function_names(path = getwd()))
  })
})

test_that("extract_exported_r_function_names() works - Empty NAMESPACE", {
  with_local_project({
    initialize_project(quiet = TRUE)

    file.create("NAMESPACE")
    expect_null(extract_exported_r_function_names(path = getwd()))
  })
})

test_that("extract_exported_r_function_names() works - No export()", {
  with_local_project({
    initialize_project(quiet = TRUE)

    namespace <- file.path(getwd(), "NAMESPACE")
    content <- c(
      "## Generated by roxygen2: do not edit by hand"
    )

    writeLines(content, namespace)

    expect_null(extract_exported_r_function_names(path = getwd()))

    namespace <- file.path(getwd(), "NAMESPACE")
    content <- c(
      "## Generated by roxygen2: do not edit by hand",
      "",
      "importFrom(usethis,ui_code)"
    )

    writeLines(content, namespace)

    expect_null(extract_exported_r_function_names(path = getwd()))
  })
})

test_that("extract_exported_r_function_names() works - With export()", {
  with_local_project({
    initialize_project(quiet = TRUE)

    namespace <- file.path(getwd(), "NAMESPACE")
    content <- c(
      "## Generated by roxygen2: do not edit by hand",
      "",
      "export(try_read)"
    )

    writeLines(content, namespace)

    expect_silent(x <- extract_exported_r_function_names(path = getwd()))

    expect_true(inherits(x, "character"))
    expect_equal(length(x), 1L)
    expect_equal(x[1], "try_read")
  })
})
